albumes = [
    {
        'id': 1,
        'nombre': 'Talento de barrio',
        'fecha': '12 de Agosto de 2008',
        'lugar': 'Puerto Rico',
        'autor': 'Daddy Yankee',
        'caratula': 'https://picsum.photos/300/300',
        'precio':'$20.000',
        'cantidad':'2',
    },
    {
        'id': 2,
        'nombre': 'Treasure EP.Fin: All to Action',
        'fecha': '8 de octubre, 2019',
        'lugar': 'Corea Del Sur',
        'autor': 'ATEEZ',
        'caratula': 'https://picsum.photos/300/300',
        'precio':'$30.000',
        'cantidad':'5',
    },
    {
        'id': 3,
        'nombre': 'Into the A to Z',
        'fecha': '24 de marzo de 2021',
        'lugar': 'Japon',
        'autor': 'ATEEZ',
        'caratula': 'https://picsum.photos/300/300',
        'precio':'$30.000',
        'cantidad':'10',
    },
    {
        'id': 4,
        'nombre': 'Treasure EP.1: All to Zero',
        'fecha': '15 de enero, 2019',
        'lugar': 'Corea Del Sur',
        'autor': 'ATEEZ',
        'caratula': 'https://picsum.photos/300/300',
        'precio':'$35.000',
        'cantidad':'7',
    },
    {
        'id': 5,
        'nombre': 'Treasure EP.3: One to All',
        'fecha': 'Lanzamiento: 10 de junio, 2019',
        'lugar': 'Corea Del Sur',
        'autor': 'ATEEZ',
        'caratula': 'https://picsum.photos/300/300',
        'precio':'$27.000',
        'cantidad':'1',
    },
    {
        'id': 6,
        'nombre': 'Zero: Fever Epilogue',
        'fecha': '10 de diciembre de 2021',
        'lugar': 'Corea Del Sur',
        'autor': 'ATEEZ',
        'caratula': 'https://picsum.photos/300/300',
        'precio':'$50.000',
        'cantidad':'8',
    },
    {
        'id': 7,
        'nombre': 'La Familia',
        'fecha': '23 de octubre de 2013',
        'lugar': 'Colombia',
        'autor': 'J Balvin',
        'caratula': 'https://picsum.photos/300/300',
        'precio':'$20.000',
        'cantidad':'2',
    },
    {
        'id': 8,
        'nombre': 'Cautivo ',
        'fecha': '2005',
        'lugar': 'Puerto Rico',
        'autor': 'Chayanne',
        'caratula': 'https://picsum.photos/300/300',
        'precio':'$70.000',
        'cantidad':'4',
    },
    {
        'id': 9,
        'nombre': 'The World Ep.1: Movement',
        'fecha': '29 de julio de 2022',
        'lugar': 'Corea Del Sur',
        'autor': 'ATEEZ',
        'caratula': 'https://picsum.photos/300/300',
        'precio':'$24.000',
        'cantidad':'9',
    },
    {
        'id': 10,
        'nombre': 'Treasure EP.Map to Answer',
        'fecha': '12 de febrero, 2020',
        'lugar': 'Japon',
        'autor': 'ATEEZ',
        'caratula': 'https://picsum.photos/300/300',
        'precio':'$30.000',
        'cantidad':'10',
    },

    
]