albumes = [
    {
        'id': 1,
        'nombre': 'Talento de barrio',
        'fecha': '12 de Agosto de 2008',
        'lugar': 'Puerto Rico',
        'autor': 'Daddy Yankee',
        'caratula': 'https://picsum.photos/400/400',
    },
    {
        'id': 2,
        'nombre': 'Talento de barrio',
        'fecha': '12 de Agosto de 2008',
        'lugar': 'Puerto Rico',
        'autor': 'Daddy Yankee',
        'caratula': 'https://picsum.photos/400/400',
    },
    {
        'id': 3,
        'nombre': 'Talento de barrio',
        'fecha': '12 de Agosto de 2008',
        'lugar': 'Puerto Rico',
        'autor': 'Daddy Yankee',
        'caratula': 'https://picsum.photos/400/400',
    },
    {
        'id': 4,
        'nombre': 'Talento de barrio',
        'fecha': '12 de Agosto de 2008',
        'lugar': 'Puerto Rico',
        'autor': 'Daddy Yankee',
        'caratula': 'https://picsum.photos/400/400',
    },
    {
        'id': 5,
        'nombre': 'Talento de barrio',
        'fecha': '12 de Agosto de 2008',
        'lugar': 'Puerto Rico',
        'autor': 'Daddy Yankee',
        'caratula': 'https://picsum.photos/400/400',
    },
    {
        'id': 6,
        'nombre': 'Talento de barrio',
        'fecha': '12 de Agosto de 2008',
        'lugar': 'Puerto Rico',
        'autor': 'Daddy Yankee',
        'caratula': 'https://picsum.photos/400/400',
    },
    {
        'id': 7,
        'nombre': 'Talento de barrio',
        'fecha': '12 de Agosto de 2008',
        'lugar': 'Puerto Rico',
        'autor': 'Daddy Yankee',
        'caratula': 'https://picsum.photos/400/400',
    },
    {
        'id': 8,
        'nombre': 'Talento de barrio',
        'fecha': '12 de Agosto de 2008',
        'lugar': 'Puerto Rico',
        'autor': 'Daddy Yankee',
        'caratula': 'https://picsum.photos/400/400',
    },
    {
        'id': 9,
        'nombre': 'Talento de barrio',
        'fecha': '12 de Agosto de 2008',
        'lugar': 'Puerto Rico',
        'autor': 'Daddy Yankee',
        'caratula': 'https://picsum.photos/400/400',
    },
    {
        'id': 10,
        'nombre': 'Talento de barrio',
        'fecha': '12 de Agosto de 2008',
        'lugar': 'Puerto Rico',
        'autor': 'Daddy Yankee',
        'caratula': 'https://picsum.photos/400/400',
    },
]